# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sebastian Mantilla
email: sebastian.mantilla@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sebastian Mantilla is a technology enthusiast, entrepreneur and information technologies professional, specialized in the development of complex, corporate applications and infrastructure. He has an integral vision of the technical, business and human aspects of the work at hand. Committed to the highest professional and human standards. He is computer literate and a creative thinker, he can also be deadline oriented with effective prioritization and time management skills, he is usually self-motivated and a team player. He is used to managing IT Infrastructure, no matter how complex it is, in a way that provides high availability, flexibility and cost effective solutions and services to users, institutions and companies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  sebastianmantilla

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
